Auth: 이메일 인증, authentication 기능 구현 완료
EntryDSM/Avengers pull request #1
Opened 2019-10-02 06:16 UTC by by09115

본 PR에서 변경된 사항은 다음과 같습니다.
- 이메일 인증 기능 구현
  - send_email(), UnauthorizedUserRepository 추가
- login, refresh, logout 기능 구현
  - sanic_jwt_extended 추가
  - RefreshTokenRepository 추가

2019-10-02 09:54 UTC, rscarrera27 requested changes

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/data/utils.py
> -            raise RedisOperationError
Why? 

as same as L33 too

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/services/__init__.py
> +def send_mail(address: str, title: str, content: str):
code in init is not recommended. please move this another place named like utils.py

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/services/auth.py
> +            raise UserAlreadyExists("")
Call exception is not required.

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/presentation/errors.py
> +    failed_to_send_email = 1400
this is server error move it to 10xx

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/services/auth.py
> +        )
some attrs of usermodel must be inserted when created 
receipt code must be inserted (get count of users)
is_paid ~ is_final_submit attrs must be inserted make them False

2019-10-02 09:54 UTC, NovemberOscar commented on avengers/services/auth.py
> +            raise UserAlreadyExists("")
same as first comment

2019-10-03 04:34 UTC, by09115 commented on avengers/data/utils.py
> -            raise RedisOperationError
![image](https://user-images.githubusercontent.com/36767009/66099521-28b79400-e5e2-11e9-93a4-038ebc0952bb.png)
![image](https://user-images.githubusercontent.com/36767009/66099556-3ff68180-e5e2-11e9-9560-313267bbd0a3.png)
첫 번째 이미지가 ""을 넣지 않았을 때, 두 번째 이미지가 ""을 넣었을 때의 결과입니다.
""를 넣지 않으면 오류 발생 시 message를 찾을 수 없다는 에러가 같이 발생해 ""를 넣었습니다.

2019-10-03 04:43 UTC, by09115 commented on avengers/services/auth.py
> +            raise UserAlreadyExists("")
마찬가지로 오류 발생 시 message를 찾을 수 없다는 에러가 같이 발생해 ""를 넣어줬습니다.

2019-10-03 05:01 UTC, by09115 commented on avengers/services/auth.py
> +            raise UserAlreadyExists("")
이 때 이메일 중복 검사를 하지 않으면 /signup/verify에서 503 error가 발생합니다. exception을 호출하지 않을 이유가 있는지 궁금합니다.

2019-10-03 07:01 UTC, NovemberOscar commented on avengers/services/auth.py
> +            raise UserAlreadyExists("")
just raise is not "call" what I meant is ()

2019-10-03 07:38 UTC, closed without merging